# Kiro CLI pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.pre.zsh"

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Load dotfiles shell configuration
[[ -f "$HOME/.dotfiles/shell/aliases.zsh" ]] && source "$HOME/.dotfiles/shell/aliases.zsh"
[[ -f "$HOME/.dotfiles/shell/functions.zsh" ]] && source "$HOME/.dotfiles/shell/functions.zsh"
[[ -f "$HOME/.dotfiles/shell/env.zsh" ]] && source "$HOME/.dotfiles/shell/env.zsh"

# PATH additions
export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"

# Kiro CLI post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/kiro-cli/shell/zshrc.post.zsh"
